drop database if exists biblio;
create database biblio;
use biblio;

CREATE TABLE `Libro` (
  `ISBN` VARCHAR(13) NOT NULL,
  `Titolo` VARCHAR(100) NOT NULL,
  `Autore` VARCHAR(100) NOT NULL,
  `Editore` VARCHAR(100) NOT NULL,
  `Prezzo` FLOAT NOT NULL,
  `Descrizione` VARCHAR(500) NOT NULL,
  `Nome_Categoria` VARCHAR(50) NOT NULL,
  `Sconto` INT DEFAULT 0,
  PRIMARY KEY (`ISBN`));
  
CREATE TABLE `Utente` (
  `Mail` VARCHAR(50) NOT NULL PRIMARY KEY,
  `Password` VARCHAR(40) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Cognome` VARCHAR(100),
  `isAdmin` BOOLEAN NULL
  );
  
CREATE TABLE `Preferiti` (
  `ISBN` VARCHAR(13) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ISBN`,`Mail`),
  FOREIGN KEY (`Mail`) REFERENCES `Utente`(`Mail`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ISBN`) REFERENCES `Libro`(`ISBN`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Login` (
  `id` VARCHAR(36) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `token` CHAR(36) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`,`mail`),
  FOREIGN KEY (`mail`) REFERENCES `Utente`(`Mail`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Ordine` (
	`id` INT AUTO_INCREMENT NOT NULL,
	`ISBN` VARCHAR(13) NOT NULL,
    `Cliente` VARCHAR(50) NOT NULL,
	PRIMARY KEY(`id`),
	FOREIGN KEY (`ISBN`) REFERENCES `Libro`(`ISBN`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`cliente`) REFERENCES `Utente`(`Mail`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `Utente` (`mail`, `password`, `nome`, `isAdmin`) VALUES ('admin@biblio.it', 'admin', 'Admin', true );
INSERT INTO `Utente`  VALUES ('maria@biblio.it', 'password', 'Maria', 'Rossi', false);

SELECT * FROM Utente;
SELECT * FROM Ordine;

INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804612841, "Il mondo segreto di Babbo Natale. Edizione Illustrata" ,"Alan Snow" ,"Mondadori", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845293894, "Lettere da Babbo Natale" ,"J.R.R. Tolkien" ,"Bompiani", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788867225088, "La Bella e la Bestia. Edizione integrale" ,"Gabrielle-Suzanna Barbot de Villenueve" ,"Ippocampo", 30, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788867224555, "Alice nel paese delle meraviglia - Al di là dello specchio. Edizione integrale" ,"Lewis Carroll" ,"Ippocampo", 30, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788867224937, "Le avventure di Pinocchio. Edizione integrale" ,"Carlo Collodi" ,"Ippocampo", 30, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788857016610, "Mano Manina. Edizione a colori" ,"Fomentini / Crovara" ,"Franco Cosimo Panini", 9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788865932773, "Rosso, blu e... Tocco, sento e imparo i colori" ,"Jenny Cooper" ,"Macro Junior", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788858027561, "Il libro della calma di Lupetto. Amico Lupo" ,"Orianne Lallemand" ,"Gribaudo", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788807923333, "Opinioni di un gatto" ,"Jutta Bauer" ,"Feltrinelli", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788898947577, "Il cuoco delle emozioni" ,"Daniele Bergesio" ,"Settenove", 17, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788856674347, "Il sigillo del gatto. Le avventure di Sherlocco" ,"Geronimo Stilton" ,"Piemme", 10.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804730422, "Storie della buonanotte per bambine ribelli. 100 donne migranti che hanno cambiato il mondo" ,"Favilli" ,"Mondadori", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804676379, "Storie della buonanotte per bambine ribelli. 100 vite di donne straordinarie" ,"Favilli/Cavallo" ,"Mondadori", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804688846, "Storie della buonanotte per bambine ribelli 2" ,"Favilli/Cavallo" ,"Mondadori", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788817149228, "La più grande" ,"Davide Morosinotto" ,"Rizzoli", 17, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788851180751, "101 cose da scrivere per fare il fenomeno e lasciare tutti di stucco con le parole anche alle medie!" ,"Annalisa Strada" ,"DeAgostini", 15.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788880334392, "Diario di una schiappa." ,"Jeff Kinney" ,"Il Castoro", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788869662584, "Diario di una schiappa. Avanti tutta!" ,"Jeff Kinney" ,"Il Castoro", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788856656572, "Nel regno della Fantasia" ,"Geronimo Stilton" ,"Piemme", 25, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788856634631, "Lo strano caso dei formaggi strapuzzoni" ,"Geronimo Stilton" ,"Piemme", 9.2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Bambini e ragazzi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788874526758, "Ragazze elettriche" ,"Naomi Alderman" , "Mondadori", 18, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804666851, "Guida galattica per gli autostoppisti" ,"Douglas Adams" ,"Mondadori", 16.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788806219369, "La strada" ,"Cormac McCarty" ,"Einaudi", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804707035, "Io, robot" ,"Isaac Asimov" ,"Mondadori", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804665298, "Fahrenheit 451" ,"Ray Bradbury" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804668169, "Cronache marziane" ,"Ray Bradbury" ,"Mondadori", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788838929106, "Solaris" ,"Stanislaw Lem" ,"Sellerio Editore Palermo", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804664994, "Ciclo delle Fondazioni. Prima Fondazione-Fondazione e impero-Seconda Fondazione" ,"Isaac Asimov" ,"Mondadori", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788834738955, "La svastica sul sole" ,"Philip K. Dick" ,"Fanucci Editore", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788834738887, "Ma gli androidi sognano pecore elettriche?" ,"Philip K. Dick" ,"Fanucci Editore", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804670520, "Il mondo nuovo" ,"Aldous Huxley" ,"Mondadori", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788806240363, "La macchina del tempo" ,"G.W. Wells" ,"Einaudi", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788822719713, "La guerra dei mondi" ,"G.W. Wells" ,"Newton Compton Editore", 4.9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788834739679, "Dune" ,"Frank Herbert" ,"Fanucci Editore", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788807884894, "Il condominio" ,"J. G. Ballard" ,"Feltrinelli", 9.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788831003384, "Harry Potter e la pietra filosofale" ,"J. K. Rowling" ,"Salani", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814515, "Harry Potter e la camera dei segreti" ,"J. K. Rowling" ,"Salani", 11, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814522, "Harry Potter e il prigioniero di Azkaban" ,"J. K. Rowling" ,"Salani", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814539, "Harry Potter e il calice di fuoco" ,"J. K. Rowling" ,"Salani", 15, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814546, "Harry Potter e l ordine della fenice" ,"J. K. Rowling" ,"Salani", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814553, "Harry Potter e il principe mezzosangue" ,"J. K. Rowling" ,"Salani", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893814560, "Harry Potter e i doni della morte" ,"J. K. Rowling" ,"Salani", 15, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788830104716, "Il Signore degli Anelli" ,"J.R.R. Tolkien" ,"Bompiani", 50, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845268342, "Lo Hobbit" ,"J.R.R. Tolkien" ,"Bompiani", 11, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845272400, "Il Silmarillion" ,"J.R.R. Tolkien" ,"Bompiani", 13.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fantasy e Fantascienza");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845296499, "Sapiens" ,"Yuval Noah Harari" ,"Bompiani", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845298752, "Homo Deus" ,"Yuval Noah Harari" ,"Bompiani", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788830100824, "21 lezioni per il XXI secolo" ,"Yuval Noah Harari" ,"Bompiani", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804727880, "Illuminismo adesso" ,"Steven Pinker" ,"Mondadori", 18, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788850254811, "Breve storia di (quasi) tutto" ,"Bill Bryson" ,"TEA", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788823521216, "Possiamo salvare il mondo, prima di cena. Perchè il clima siamo noi" ,"Jonathan Safran Foer" ,"Guanda", 18, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788845932984, "Essere una macchina." ,"Mark O Connell" ,"Adelphi", 19, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788867224012, "Infografica della Seconda Guerra Mondiale" ,"AAVV" ,"Ippocampo", 25, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804637493, "Il declino della violenza" ,"Steven Pinker" ,"Mondadori", 21, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788806219222, "Armi, acciaio, malattie" ,"Jared Diamond" ,"Einaudi", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788807883774, "Sud e magia" ,"Ernesto De Martino" ,"Feltrinelli", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Saggistica");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804668237, "1984" ,"George Orwell" ,"Mondadori", 14, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788807900716, "Frankenstein" ,"Mary Shelley" ,"Feltrinelli", 9.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804721871, "La nona casa" ,"Leigh Bardugo" ,"Mondadori", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804645731, "Giappone" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti del Giappone", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804612331, "Francia" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti della Francia", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788345645731, "Spagna" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti della Spagna", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788674345731, "India" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti dell India", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788523645731, "Corea" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti della Corea", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804325645, "Roma" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti di Roma", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788822345623, "Sicilia" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti della Sicilia", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788423454331, "Venezia e il Veneto" ,"AAVV" ,"Lonely Planet", 20, "Itinerari e segreti di Venezia e il Veneto", "Viaggi");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243433531, "Orgoglio e pregiudizio" ,"Jane Austen" ,"Einaudi", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788123433531, "Cime tempestose" ,"Emily Bronte" ,"Feltrinelli", 10, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9781245562344, "Alla ricerca del tempo perduto" ,"Marcel Proust" ,"Mondadori", 30, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243234546, "L amico ritrovato" ,"Fred Uhlman" ,"Feltrinelli", 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243234562, "Tenera è la notte" ,"Francis Scott Fitzgerald" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243243566, "Il grande Gatsby" ,"Francis Scott Fitzgerald" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788242345432, "La peste" ,"Albert Camus" ,"Bompiani", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa straniera");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243245621, "Uno, nessuno e centomila" ,"Luigi Pirandello" ,"Einaudi", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243432345, "Novelle per un anno" ,"Luigi Pirandello" ,"Newton Compton Editore", 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243324531, "Il fu Mattia Pascal" ,"Luigi Pirandello" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788123124131, "I Malavoglia" ,"Giovanni Verga" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788242141213, "Mastro Don Gesualdo" ,"Giovanni Verga" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788124453223, "La coscienza di Zeno" ,"Italo Svevo" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788881232342, "Divina Commedia" ,"Dante Alighieri" ,"Newton Compton Editore", 5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788232452222, "Se una notte d inverno un viaggiatore" ,"Italo Calvino" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788243214531, "Il barone rampante" ,"Italo Calvino" ,"Mondadori", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788342553531, "Il nome della rosa" ,"Umberto Eco" ,"Bompiani", 12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788245335872, "L isola di Arturo" ,"Elsa Morante" ,"Einaudi", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Narrativa italiana");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864200330, "Le bizzarre avventure di JOJO - PHANTOM BLOOD 1" ,"Hirohiko Araki" ,"Star Comics", 7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864200415, "Le bizzarre avventure di JOJO - PHANTOM BLOOD 2" ,"Hirohiko Araki" ,"Star Comics", 7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864200439, "Le bizzarre avventure di JOJO - PHANTOM BLOOD 3 (M3)" ,"Hirohiko Araki" ,"Star Comics", 7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788891286840, "Beastars Vol 1" ,"Paru Itagaki" ,"Panini Comics", 5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788891282124, "Beastars Vol 8" ,"Paru Itagaki" ,"Panini Comics", 5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788891286324, "Beastars Vol 12" ,"Paru Itagaki" ,"Panini Comics", 5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864678415, "Demon Slayer Vol 1" ,"Koyoharu Gotoge" ,"Star Comics", 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864200243, "Demon Slayer Vol 2" ,"Koyoharu Gotoge" ,"Star Comics", 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788864200343, "Demon Slayer Vol 3" ,"Koyoharu Gotoge" ,"Star Comics", 8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788893517140, "V per Vendetta" ,"Alan Moore" ,"Lion", 25.5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Fumetti e manga");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804726685, "Il tempo della clemenza" ,"John Grisham" ,"Mondadori", 22, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804717638, "Gli invisibili" ,"Valerio Varesi" ,"Mondadori", 16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788842819813, "Psyco" ,"Robert Bloch" ,"Il Saggiatore", 15, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804710318, "Dieci piccoli indiani" ,"Agatha Cristie" ,"Mondadori", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804679387, "Assassinio sul Nilo" ,"Agatha Cristie" ,"Mondadori", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788868360818, "Le notti di Salem" ,"Stephen King" ,"Sperling & Kupfer", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788820067748, "Pet Sematary" ,"Stephen King" ,"Sperling & Kupfer", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788820068288, "Se scorre il sangue" ,"Stephen King" ,"Sperling & Kupfer", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788804671619, "Dracula" ,"Bram Stoker" ,"Mondadori", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");
INSERT INTO `Libro` (`ISBN`, `Titolo`, `Autore`, `Editore`, `Prezzo`, `Descrizione`, `Nome_Categoria`) VALUE (9788868365622, "It" ,"Stephen King" ,"Sperling & Kupfer", 20, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "Gialli Thriller e Horror");

SELECT * FROM `Libro`;

